package interfaz;
// Autor @DavidBP014
// Redimensionar imagenes
import backend.Articulo;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class frmArticulos extends javax.swing.JInternalFrame {

    public frmArticulos() {
        initComponents();

        //Iniciar los valores del tipo de articulo
        for (int i = 0; i < 3; i++) {
            list_tipo.addItem(TipoArticulo[i]);
        }

        list_genero.setEnabled(false);
    }

    //Arrays para Tipo de articulo
    String TipoArticulo[] = {"", "Pelicula", "Videojuego"};
    String generoPeliculas[] = {"", "Documental", "Biográfico", "Musical", "Comedia", "Acción", "Drama", "Terror"};
    String generoVideoJuegos[] = {"", "Aventura", "Estrategico", "RPG", "Deportivo", "Carreras", "Terror"};

    //Permitir solo numeros en el input
    private void inputNumeros(java.awt.event.KeyEvent evt) {
        char key = (char) evt.getKeyChar();
        if (Character.isDigit(key)) {
            evt.setKeyChar(key);
        } else {
            evt.consume();
        }
    }

    //Detectar la tecla enter
    private boolean teclaEnter(java.awt.event.KeyEvent evt) {
        boolean result = false;
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            result = true;
        }
        return result;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        contenedorPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_codigo = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        lbl_titulo = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JTextField();
        lbl_tipo = new javax.swing.JLabel();
        lbl_precioVenta = new javax.swing.JLabel();
        lbl_cantidad = new javax.swing.JLabel();
        txt_buscarCliente = new javax.swing.JTextField();
        btn_buscarArticulo = new javax.swing.JButton();
        btn_registrarArticulo = new javax.swing.JButton();
        btn_actualizarArticulo = new javax.swing.JButton();
        btn_eliminarArticulo = new javax.swing.JButton();
        lbl_genero = new javax.swing.JLabel();
        list_tipo = new javax.swing.JComboBox<>();
        list_genero = new javax.swing.JComboBox<>();
        txt_precioVenta = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        cont_titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cont_logo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        PiedePagina = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);
    }
};